name: Deploy

on:
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@c952173
    - uses: actions/setup-node@c6fd00c
      with:
        node-version: '12.19.1'
    - run: npm test
  deploy-client:
    needs: test
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: client
    steps:
    - uses: actions/checkout@c952173
    - uses: actions/setup-node@c6fd00c
      with:
        node-version: '12.19.1'
    - uses: bahmutov/npm-install@v1
      with:
          working-directory: client
    - run: npm run build
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_PATH: ./client
  deploy-server:
    needs: test
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v2
        with:
          working-directory: api
      - uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "think-fast-api"
          heroku_email: "admin@sikaeducation.com"
          user_docker: true
          appdir: api
